-   id: python-check-blanket-noqa
    name: Check blanket noqa
    description: 'Enforce that `noqa` annotations always occur with specific codes'
    entry: '# noqa(?!: )'
    language: pygrep
    types: [python]
-   id: python-check-mock-methods
    name: check for not-real mock methods
    description: >-
        Prevent common mistakes of `assert mck.not_called()`, `assert mck.called_once_with(...)` and
        and `mck.assert_called`.
    language: pygrep
    entry: '(assert .*\.(not_called|called\w*)|\.assert_(not_called|called\w*)($|[^(\w]))'
    types: [python]
-   id: python-no-log-warn
    name: use logger.warning(
    description: 'A quick check for the deprecated `.warn()` method of python loggers'
    entry: '\.warn\('
    language: pygrep
    types: [python]
-   id: python-use-type-annotations
    name: type annotations not comments
    description: 'Enforce that python3.6+ type annotations are used instead of type comments'
    entry: '# type(?!: *ignore *($|#))'
    language: pygrep
    types: [python]
-   id: rst-backticks
    name: rst ``code`` is two backticks
    description: 'Detect common mistake of using single backticks when writing rst'
    entry: ' `[^`]+[^_]`([^_]|$)'
    language: pygrep
    types: [rst]
