language: python
python: 3.6
install: pip install pre-commit pytest
script:
    - pytest tests
    - pre-commit run --all-files
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
